// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package database

import (
	"context"
	"time"
)

const addNewEWMA = `-- name: AddNewEWMA :exec
INSERT INTO ewma (product_id, ewma, recorded_at)
VALUES ($1, $2, $3)
`

type AddNewEWMAParams struct {
	ProductID  string
	Ewma       float64
	RecordedAt time.Time
}

func (q *Queries) AddNewEWMA(ctx context.Context, arg AddNewEWMAParams) error {
	_, err := q.db.ExecContext(ctx, addNewEWMA, arg.ProductID, arg.Ewma, arg.RecordedAt)
	return err
}

const getRecentProductEWMA = `-- name: GetRecentProductEWMA :one
SELECT id, product_id, recorded_at, ewma FROM ewma WHERE product_id = $1
ORDER BY recorded_at DESC LIMIT 1
`

func (q *Queries) GetRecentProductEWMA(ctx context.Context, productID string) (Ewma, error) {
	row := q.db.QueryRowContext(ctx, getRecentProductEWMA, productID)
	var i Ewma
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.RecordedAt,
		&i.Ewma,
	)
	return i, err
}
