// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
)

const createStaff = `-- name: CreateStaff :exec
INSERT INTO staffs (id, first_name, last_name, pword, is_manager, username)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
`

type CreateStaffParams struct {
	FirstName string
	LastName  string
	Pword     string
	IsManager bool
	Username  string
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) error {
	_, err := q.db.ExecContext(ctx, createStaff,
		arg.FirstName,
		arg.LastName,
		arg.Pword,
		arg.IsManager,
		arg.Username,
	)
	return err
}

const getLevel = `-- name: GetLevel :one
SELECT is_manager FROM staffs WHERE id = $1
`

func (q *Queries) GetLevel(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, getLevel, id)
	var is_manager bool
	err := row.Scan(&is_manager)
	return is_manager, err
}

const loginUser = `-- name: LoginUser :one
SELECT id, username, is_manager, pword
FROM staffs WHERE username = $1
`

type LoginUserRow struct {
	ID        string
	Username  string
	IsManager bool
	Pword     string
}

func (q *Queries) LoginUser(ctx context.Context, username string) (LoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, loginUser, username)
	var i LoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsManager,
		&i.Pword,
	)
	return i, err
}

const tryLogin = `-- name: TryLogin :one
SELECT id, first_name, last_name, dob, username, pword, is_manager FROM staffs
WHERE username = $1 and pword = $2
`

type TryLoginParams struct {
	Username string
	Pword    string
}

func (q *Queries) TryLogin(ctx context.Context, arg TryLoginParams) (Staff, error) {
	row := q.db.QueryRowContext(ctx, tryLogin, arg.Username, arg.Pword)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Username,
		&i.Pword,
		&i.IsManager,
	)
	return i, err
}
