// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
)

const getLevel = `-- name: GetLevel :one
SELECT is_manager FROM staffs WHERE id = $1
`

func (q *Queries) GetLevel(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, getLevel, id)
	var is_manager bool
	err := row.Scan(&is_manager)
	return is_manager, err
}

const loginUser = `-- name: LoginUser :one
SELECT id, username, is_manager
FROM staffs WHERE username = $1 AND pword = $2
`

type LoginUserParams struct {
	Username string
	Pword    string
}

type LoginUserRow struct {
	ID        string
	Username  string
	IsManager bool
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (LoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, loginUser, arg.Username, arg.Pword)
	var i LoginUserRow
	err := row.Scan(&i.ID, &i.Username, &i.IsManager)
	return i, err
}
