// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package database

import (
	"context"
)

const getInventory = `-- name: GetInventory :one
SELECT product_id, quantity_on_hand, last_updated FROM inventory WHERE product_id = $1
`

func (q *Queries) GetInventory(ctx context.Context, productID string) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, productID)
	var i Inventory
	err := row.Scan(&i.ProductID, &i.QuantityOnHand, &i.LastUpdated)
	return i, err
}

const newInventory = `-- name: NewInventory :exec
INSERT INTO inventory (product_id, quantity_on_hand, last_updated)
VALUES ($1, $2, NOW())
`

type NewInventoryParams struct {
	ProductID      string
	QuantityOnHand int32
}

func (q *Queries) NewInventory(ctx context.Context, arg NewInventoryParams) error {
	_, err := q.db.ExecContext(ctx, newInventory, arg.ProductID, arg.QuantityOnHand)
	return err
}

const updatedInventory = `-- name: UpdatedInventory :exec
UPDATE inventory SET quantity_on_hand = $2, last_updated = NOW()
WHERE product_id = $1
`

type UpdatedInventoryParams struct {
	ProductID      string
	QuantityOnHand int32
}

func (q *Queries) UpdatedInventory(ctx context.Context, arg UpdatedInventoryParams) error {
	_, err := q.db.ExecContext(ctx, updatedInventory, arg.ProductID, arg.QuantityOnHand)
	return err
}
