// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Adjustment struct {
	ID              int32
	ProductID       string
	QuantityChanged int32
	Reason          string
	AdjustmentDate  sql.NullTime
}

type Inventory struct {
	ProductID      string
	QuantityOnHand int32
	LastUpdated    sql.NullTime
}

type Product struct {
	ID           string
	ProductName  string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Price        float64
	ReorderLevel int32
}

type Purchase struct {
	ID            string
	ProductID     string
	QuantityAdded int32
	PurchaseDate  sql.NullTime
}

type Sale struct {
	ID          int32
	TotalAmount float64
	SaleDate    sql.NullTime
}

type SalesItem struct {
	ID           int32
	SalesID      int32
	ProductID    string
	QuantitySold int32
	PriceAtSale  float64
}
