// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Adjustment struct {
	ID              int32
	ProductID       string
	QuantityChanged int32
	Reason          string
	AdjustmentDate  time.Time
}

type Ewma struct {
	ID         int64
	ProductID  string
	RecordedAt time.Time
	Ewma       float64
}

type Inventory struct {
	ProductID      string
	QuantityOnHand int32
	LastUpdated    time.Time
}

type Product struct {
	ID           string
	ProductName  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Price        float64
	ReorderLevel int32
}

type Productdetail struct {
	ID             string
	ProductName    string
	QuantityOnHand int32
	Price          float64
	ReorderLevel   int32
	StockStatus    int32
}

type Purchase struct {
	ID            string
	ProductID     string
	QuantityAdded int32
	PurchaseDate  time.Time
}

type Sale struct {
	ID          int32
	TotalAmount float64
	SaleDate    time.Time
}

type SalesItem struct {
	ID           int32
	SalesID      int32
	ProductID    string
	QuantitySold int32
	PriceAtSale  float64
}
