// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, created_at, updated_at, product_name, reorder_level, price)
VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2, $3
)
RETURNING id, product_name, created_at, updated_at, price, reorder_level
`

type CreateProductParams struct {
	ProductName  string
	ReorderLevel int32
	Price        float64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.ProductName, arg.ReorderLevel, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Price,
		&i.ReorderLevel,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getFullProductDetail = `-- name: GetFullProductDetail :many
SELECT 
  p.id,
  p.product_name,
  i.quantity_on_hand,
  p.price,
  p.reorder_level,
  CASE 
    WHEN i.quantity_on_hand = 0 THEN -2
    WHEN i.quantity_on_hand <= p.reorder_level THEN -1
    WHEN i.quantity_on_hand <= p.reorder_level * 1.5 THEN 0
    ELSE 1
  END AS stock_status
FROM products p
JOIN inventory i
ON p.id = i.product_id
`

type GetFullProductDetailRow struct {
	ID             string
	ProductName    string
	QuantityOnHand int32
	Price          float64
	ReorderLevel   int32
	StockStatus    int32
}

func (q *Queries) GetFullProductDetail(ctx context.Context) ([]GetFullProductDetailRow, error) {
	rows, err := q.db.QueryContext(ctx, getFullProductDetail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullProductDetailRow
	for rows.Next() {
		var i GetFullProductDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.QuantityOnHand,
			&i.Price,
			&i.ReorderLevel,
			&i.StockStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, product_name, created_at, updated_at, price, reorder_level FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Price,
		&i.ReorderLevel,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, product_name, created_at, updated_at, price, reorder_level FROM products
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Price,
			&i.ReorderLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductPrice = `-- name: UpdateProductPrice :exec
UPDATE products SET price = $2 WHERE id = $1
`

type UpdateProductPriceParams struct {
	ID    string
	Price float64
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) error {
	_, err := q.db.ExecContext(ctx, updateProductPrice, arg.ID, arg.Price)
	return err
}
