// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchases.sql

package database

import (
	"context"
)

const createAdjustments = `-- name: CreateAdjustments :one
INSERT INTO adjustments (product_id, quantity_changed, reason, adjustment_date)
VALUES ($1, $2, $3, NOW())
Returning product_id, quantity_changed
`

type CreateAdjustmentsParams struct {
	ProductID       string
	QuantityChanged int32
	Reason          string
}

type CreateAdjustmentsRow struct {
	ProductID       string
	QuantityChanged int32
}

func (q *Queries) CreateAdjustments(ctx context.Context, arg CreateAdjustmentsParams) (CreateAdjustmentsRow, error) {
	row := q.db.QueryRowContext(ctx, createAdjustments, arg.ProductID, arg.QuantityChanged, arg.Reason)
	var i CreateAdjustmentsRow
	err := row.Scan(&i.ProductID, &i.QuantityChanged)
	return i, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (id, product_id, quantity_added, purchase_date)
VALUES (gen_random_uuid(), $1, $2, NOW())
Returning id
`

type CreatePurchaseParams struct {
	ProductID     string
	QuantityAdded int32
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createPurchase, arg.ProductID, arg.QuantityAdded)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deletePurchase = `-- name: DeletePurchase :exec
DELETE FROM purchases WHERE id = $1
`

func (q *Queries) DeletePurchase(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePurchase, id)
	return err
}
