// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchases.sql

package database

import (
	"context"
)

const createPurchase = `-- name: CreatePurchase :exec
INSERT INTO purchases (id, product_id, quantity_added, purchase_date)
VALUES (gen_random_uuid(), $1, $2, NOW())
`

type CreatePurchaseParams struct {
	ProductID     string
	QuantityAdded int32
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) error {
	_, err := q.db.ExecContext(ctx, createPurchase, arg.ProductID, arg.QuantityAdded)
	return err
}
