// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package database

import (
	"context"
)

const createAdjustment = `-- name: CreateAdjustment :one
INSERT INTO adjustments (product_id, quantity_changed, reason, adjustment_date)
VALUES ($1, $2, $3, NOW()) RETURNING id
`

type CreateAdjustmentParams struct {
	ProductID       string
	QuantityChanged int32
	Reason          string
}

func (q *Queries) CreateAdjustment(ctx context.Context, arg CreateAdjustmentParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createAdjustment, arg.ProductID, arg.QuantityChanged, arg.Reason)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSales = `-- name: CreateSales :one
INSERT INTO sales (total_amount, sale_date)
VALUES ($1, NOW()) RETURNING id
`

func (q *Queries) CreateSales(ctx context.Context, totalAmount float64) (int32, error) {
	row := q.db.QueryRowContext(ctx, createSales, totalAmount)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSalesItems = `-- name: CreateSalesItems :exec
INSERT INTO sales_items (sales_id, product_id, quantity_sold, price_at_sale)
VALUES ($1, $2, $3, $4)
`

type CreateSalesItemsParams struct {
	SalesID      int32
	ProductID    string
	QuantitySold int32
	PriceAtSale  float64
}

func (q *Queries) CreateSalesItems(ctx context.Context, arg CreateSalesItemsParams) error {
	_, err := q.db.ExecContext(ctx, createSalesItems,
		arg.SalesID,
		arg.ProductID,
		arg.QuantitySold,
		arg.PriceAtSale,
	)
	return err
}

const deleteAdjustment = `-- name: DeleteAdjustment :exec
DELETE FROM adjustments WHERE id = $1
`

func (q *Queries) DeleteAdjustment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAdjustment, id)
	return err
}

const deleteSales = `-- name: DeleteSales :exec
DELETE FROM sales WHERE id = $1
`

func (q *Queries) DeleteSales(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSales, id)
	return err
}

const deleteSalesItems = `-- name: DeleteSalesItems :exec
DELETE FROM sales_items WHERE sales_id = $1
`

func (q *Queries) DeleteSalesItems(ctx context.Context, salesID int32) error {
	_, err := q.db.ExecContext(ctx, deleteSalesItems, salesID)
	return err
}

const getProductInventory = `-- name: GetProductInventory :one
SELECT p.id, p.product_name, p.price, i.quantity_on_hand 
FROM products p
JOIN inventory i ON p.id = i.product_id
WHERE p.id = $1
`

type GetProductInventoryRow struct {
	ID             string
	ProductName    string
	Price          float64
	QuantityOnHand int32
}

func (q *Queries) GetProductInventory(ctx context.Context, id string) (GetProductInventoryRow, error) {
	row := q.db.QueryRowContext(ctx, getProductInventory, id)
	var i GetProductInventoryRow
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.Price,
		&i.QuantityOnHand,
	)
	return i, err
}
