// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package database

import (
	"context"
)

const searchProductForCheckout = `-- name: SearchProductForCheckout :many
SELECT p.id, p.product_name, p.price, i.quantity_on_hand
FROM products p JOIN inventory i ON p.id = i.product_id
WHERE to_tsvector('english', p.product_name) @@ websearch_to_tsquery('english', $1)
OR p.product_name ILIKE '%' || $1 || '%'
`

type SearchProductForCheckoutRow struct {
	ID             string
	ProductName    string
	Price          float64
	QuantityOnHand int32
}

// WHERE to_tsvector(p.product_name) @@ plainto_tsquery($1);
func (q *Queries) SearchProductForCheckout(ctx context.Context, websearchToTsquery string) ([]SearchProductForCheckoutRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProductForCheckout, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductForCheckoutRow
	for rows.Next() {
		var i SearchProductForCheckoutRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.Price,
			&i.QuantityOnHand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
